language: python
python:
  - "2.7"
  - "3.5"
install: 
  - pip install -r requirements.txt
  - pip install pydocstyle
  - pip install pyflakes
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
script:
  - python setup.py install
  - pyflakes setup.py
  - nosetests --with-coverage tests
  - pydocstyle
after_success:  
  - coveralls
